### PR TITLE
Added initial logging for download history

### PR DESCRIPTION
**Pull request by silascutler**
Started progress on issue #18 .  Changes made include:

- Added DownloadHistory model and included with config
- Added initial logging functionality to downloads. 

I wanted to start off with defining a schema and if it looks good, I'll continue building this feature.

### CODE REVIEW

**Review by Forceu — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution! There are some changes necessary:

- Please increase config version to 8 and set change the `updateConfig` function to create a new map if previous version is below 8
- Also the test seems to time out, so you are probably running `getSettings()` while the settings object is still being locked
- If the server is behind a proxy, an incorrect IP will be passed, however I can change that myself.

**Comment by silascutler** [comment]
Thanks @Forceu.  The configuration version check has been updated to version 8.  I also attempted to write tests for the History function, but may need some help as I have not written Go unit tests before and am unfamiliar with how to test properly

**Comment by Forceu** [comment]
Don't worry about writing tests, it is however important that the original tests don't fail. You can run the tests with `go test ./... --tags=test,awsmock` in the main directory. In two or three days I have some time for a closer look at the code as well, so I could support you with this PR :)

**Comment by Forceu** [comment]
I added the feature in 6cffccb3bef35c95b275c500b52dda8a297cbbbb with a slimmer and non-blocking version. Thank you very much for your help however! :)

**Pull request closed without merging**
